[package]
name = "scytheric/lunar-cmdr"
description = "Heavily modified version of Cmdr to suite my needs."
version = "1.12.1"
license = "MIT"
authors = ["evaera", "Scytheric"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["assets", "docs"]

[dependencies]
